// Auto-generated list of every page on the site, for the site search tool.
// Regenerate by pulling routes from App.tsx if you add/remove many pages
// at once — otherwise just add/edit entries here directly, it's a plain list.

export interface SearchEntry {
  path: string;
  label: string;
}

export const siteSearchIndex: SearchEntry[] = [
  { path: "/afh-club/building-inspection", label: "AFH Building Inspection" },
  { path: "/afh-club/buying-selling", label: "AFH Buying Selling" },
  { path: "/afh-club/calculators", label: "AFH Calculators" },
  { path: "/afh-club", label: "AFH Club" },
  { path: "/afh-club/costs-fees", label: "AFH Costs Fees" },
  { path: "/afh-club/for-sale/edmonds-wa", label: "AFH For Sale Edmonds WA" },
  { path: "/afh-club/for-sale/kirkland-wa", label: "AFH For Sale Kirkland WA" },
  { path: "/afh-club/for-sale/lynnwood-wa", label: "AFH For Sale Lynnwood WA" },
  { path: "/afh-club/for-sale/puyallup-wa", label: "AFH For Sale Puyallup WA" },
  { path: "/afh-club/for-sale/renton-wa", label: "AFH For Sale Renton WA" },
  { path: "/afh-club/for-sale/seattle-wa", label: "AFH For Sale Seattle WA" },
  { path: "/afh-club/find-a-professional", label: "AFH Find Professional" },
  { path: "/afh-club/getting-started", label: "AFH Getting Started" },
  { path: "/afh-club/licensing-certification", label: "AFH Licensing Certification" },
  { path: "/afh-club/listings", label: "AFH Listings" },
  { path: "/afh-club/management-companies", label: "AFH Management Companies" },
  { path: "/afh-marketplace", label: "AFH Marketplace" },
  { path: "/afh-club/ownership-structure", label: "AFH Ownership Structure" },
  { path: "/afh-club/real-estate-broker", label: "AFH Real Estate Broker" },
  { path: "/afh-club/regulations-compliance", label: "AFH Regulations Compliance" },
  { path: "/afh-club/resources", label: "AFH Resources" },
  { path: "/afh-club/selling-your-business-at-retirement", label: "AFH Selling Your Business At Retirement" },
  { path: "/afh-submit", label: "AFH Submit" },
  { path: "/afh-club/training-education", label: "AFH Training Education" },
  { path: "/afh-club/afh-valuation-estimator", label: "AFH Valuation Estimator" },
  { path: "/afh-club/afh-roi-calculator", label: "AFH ROI Calculator" },
  { path: "/about", label: "About" },
  { path: "/senior-living/adult-family-homes", label: "Adult Family Homes" },
  { path: "/articles/affordable-senior-housing", label: "Affordable Senior Housing" },
  { path: "/senior-living/aging-in-place", label: "Aging In Place" },
  { path: "/articles/aging-in-place", label: "Aging In Place Article" },
  { path: "/aging-in-place-staying-home-safely", label: "Aging In Place Staying Home Safely" },
  { path: "/aging-life-care-managers", label: "Aging Life Care Managers" },
  { path: "/guides/appraisal-before-selling-inherited-property", label: "Appraisal Before Selling" },
  { path: "/guides/appraisal-vs-cma", label: "Appraisal Vs Cma" },
  { path: "/articles", label: "Articles Index" },
  { path: "/senior-living/assisted-living", label: "Assisted Living" },
  { path: "/senior-living/assisted-living-communities", label: "Assisted Living Communities" },
  { path: "/professionals/attorneys", label: "Attorneys Directory" },
  { path: "/attorneys/for-elder-law-attorneys", label: "Attorneys For Elder Law Attorneys" },
  { path: "/attorneys/for-family-law-attorneys", label: "Attorneys For Family Law Attorneys" },
  { path: "/attorneys/for-real-estate-attorney", label: "Attorneys For Real Estate Attorney" },
  { path: "/bellevue-probate-estate-real-estate", label: "Bellevue Probate Estate" },
  { path: "/bellingham-probate-estate-real-estate", label: "Bellingham Probate Estate" },
  { path: "/benton-county", label: "Benton County" },
  { path: "/counties/benton", label: "Benton County" },
  { path: "/building-your-trusted-professional-team", label: "Building Your Trusted Professional Team" },
  { path: "/resources/cpas-financial-advisors", label: "CPAs & Financial Advisors" },
  { path: "/professionals/care-managers", label: "Care Managers" },
  { path: "/articles/ccrc-costs", label: "Ccrc Costs" },
  { path: "/helping-an-aging-parent", label: "Helping an Aging Parent" },
  { path: "/clark-county", label: "Clark County" },
  { path: "/counties/clark", label: "Clark County" },
  { path: "/client-stories", label: "Client Stories" },
  { path: "/contact", label: "Contact" },
  { path: "/cost-of-care-calculator", label: "Cost Of Care Calculator" },
  { path: "/counties", label: "Counties" },
  { path: "/counties/cowlitz", label: "Cowlitz County" },
  { path: "/cowlitz-county", label: "Cowlitz County" },
  { path: "/date-of-death-valuation-property-appraisals", label: "Date Of Death Valuation Property Appraisals" },
  { path: "/disclaimer", label: "Disclaimer" },
  { path: "/downsizing-preparing-for-transition", label: "Downsizing Preparing For Transition" },
  { path: "/estate-probate-inherited-property/first-steps", label: "First Steps After a Death" },
  { path: "/estate-probate-inherited-property/preparing-the-property", label: "Preparing the Property for Sale" },
  { path: "/estate-probate-inherited-property/probate-and-legal-authority", label: "Understanding Probate & Legal Authority" },
  { path: "/estate-probate-inherited-property/professional-team", label: "Building Your Professional Team" },
  { path: "/estate-probate-inherited-property/property-value", label: "Understanding the Property's Value" },
  { path: "/estate-probate-inherited-property/what-to-do-with-the-property", label: "Deciding What to Do With the Property" },
  { path: "/executor-responsibilities-first-steps/common-mistakes", label: "Common Executor Mistakes" },
  { path: "/executor-responsibilities-first-steps/first-30-days", label: "Your First 30 Days as Executor" },
  { path: "/executor-responsibilities-first-steps/legal-duties", label: "Understanding Your Legal Duties as Executor" },
  { path: "/executor-responsibilities-first-steps/property-decisions", label: "What to Do With Real Estate in the Estate" },
  { path: "/executor-responsibilities-first-steps/when-you-need-extra-help", label: "When You Need Extra Help" },
  {
    path: "/executor-responsibilities-first-steps/working-with-professionals",
    label: "Working With Professionals",
  },
  { path: "/estate-liquidation", label: "Estate Liquidation" },
  { path: "/estate-liquidation/learn-more", label: "Estate Liquidation Learn More" },
  { path: "/estate-liquidators", label: "Estate Liquidators" },
  { path: "/estate-planning-powers-of-attorney", label: "Estate Planning Powers Of Attorney" },
  { path: "/estate-probate-inherited-property", label: "Estate Probate Inherited Property" },
  { path: "/guides/estate-property-repairs-before-sale", label: "Estate Property Repairs" },
  { path: "/professionals/estate-sale", label: "Estate Sale" },
  { path: "/resources/estate-sale-companies", label: "Estate Sale Companies" },
  { path: "/everett-probate-estate-real-estate", label: "Everett Probate Estate" },
  { path: "/guides/executor-first-steps-house", label: "Executor First Steps House" },
  { path: "/executor-responsibilities-first-steps", label: "Executor Responsibilities First Steps" },
  { path: "/guides/executor-sell-house-before-probate-washington", label: "Executor Sell Before Probate" },
  { path: "/executors", label: "Executors" },
  { path: "/executors/executors-guide", label: "Executors Guide" },
  { path: "/faq", label: "FAQ" },
  { path: "/featured-senior-move-managers", label: "Featured Senior Move Managers" },
  { path: "/professionals/financial-planners", label: "Financial Planners" },
  { path: "/for-attorneys", label: "For Attorneys" },
  { path: "/for-attorneys/how-it-works", label: "For Attorneys How It Works" },
  { path: "/for-cpas", label: "For CP As" },
  { path: "/attorneys/for-divorce-attorneys", label: "For Divorce Attorneys" },
  { path: "/for-attorneys/divorce-attorneys", label: "For Divorce Attorneys" },
  { path: "/for-divorce-attorneys", label: "For Divorce Attorneys" },
  { path: "/for-attorneys/elder-law-attorneys", label: "For Elder Law Attorneys" },
  { path: "/for-elder-law-attorneys", label: "For Elder Law Attorneys" },
  { path: "/for-attorneys/estate-planning-attorneys", label: "For Estate Planning Attorneys" },
  { path: "/for-estate-planning-attorneys", label: "For Estate Planning Attorneys" },
  { path: "/for-attorneys/family-law-attorneys", label: "For Family Law Attorneys" },
  { path: "/for-family-law-attorneys", label: "For Family Law Attorneys" },
  { path: "/for-financial-planners", label: "For Financial Planners" },
  { path: "/for-attorneys/probate-attorneys", label: "For Probate Attorneys" },
  { path: "/for-probate-attorneys", label: "For Probate Attorneys" },
  { path: "/for-attorneys/real-estate-attorneys", label: "For Real Estate Attorneys" },
  { path: "/real-estate-attorneys", label: "For Real Estate Attorneys" },
  { path: "/counties/franklin", label: "Franklin County" },
  { path: "/franklin-county", label: "Franklin County" },
  { path: "/gray-divorce", label: "Gray Divorce" },
  { path: "/counties/grays-harbor", label: "Grays Harbor County" },
  { path: "/grays-harbor-county", label: "Grays Harbor County" },
  { path: "/grey-divorce", label: "Grey Divorce" },
  { path: "/guides-and-resources", label: "Guides & Articles" },
  { path: "/guides/heirs-disagree-selling-house", label: "Heirs Disagree Selling" },
  { path: "/hero-test", label: "Hero Test" },
  { path: "/professionals/home-preparation", label: "Home Preparation" },
  { path: "/home-new", label: "Homepage New" },
  { path: "/guides/how-long-sell-probate-property", label: "How Long Sell Probate Property" },
  { path: "/guides/how-probate-real-estate-works", label: "How Probate Real Estate Works" },
  { path: "/how-the-process-works", label: "How The Process Works" },
  { path: "/articles/how-to-choose-senior-housing", label: "How To Choose Senior Housing" },
  { path: "/senior-living/independent-living", label: "Independent Living" },
  { path: "/articles/independent-living-costs", label: "Independent Living Costs" },
  { path: "/guides/inherited-house-washington", label: "Inherited House Washington" },
  { path: "/counties/island", label: "Island County" },
  { path: "/island-county", label: "Island County" },
  { path: "/counties/jefferson", label: "Jefferson County" },
  { path: "/jefferson-county", label: "Jefferson County" },
  { path: "/join-the-network", label: "Join The Network" },
  { path: "/counties/king", label: "King County" },
  { path: "/king-county", label: "King County" },
  { path: "/counties/kitsap", label: "Kitsap County" },
  { path: "/kitsap-county", label: "Kitsap County" },
  { path: "/long-term-care/finding-care-roomandcare", label: "Finding Care: RoomAndCare.com" },
  { path: "/long-term-care/hospital-discharge-planning", label: "Planning Your Hospital Discharge" },
  { path: "/long-term-care/how-to-choose-care-settings", label: "How to Choose Between Care Settings" },
  { path: "/long-term-care/medicaid-and-long-term-care", label: "Medicaid & Long-Term Care in Washington State" },
  { path: "/long-term-care/nurse-delegation", label: "The Nurse Delegation Program in Washington State" },
  { path: "/long-term-care/nursing-homes", label: "Nursing Homes in Washington State" },
  { path: "/long-term-care/short-term-nursing-home-stays", label: "Short-Term Nursing Home Stays" },
  { path: "/long-term-care/wa-cares", label: "WA Cares Fund" },
  { path: "/lenders-and-financing-specialists", label: "Lenders Financing Specialists" },
  { path: "/counties/lewis", label: "Lewis County" },
  { path: "/lewis-county", label: "Lewis County" },
  { path: "/long-term-care", label: "Long Term Care Options" },
  { path: "/counties/mason", label: "Mason County" },
  { path: "/mason-county", label: "Mason County" },
  { path: "/medicare-providers", label: "Medicare Providers" },
  { path: "/senior-living/memory-care", label: "Memory Care" },
  { path: "/articles/memory-care-costs", label: "Memory Care Costs" },
  { path: "/mortgage-lenders", label: "Mortgage Lenders" },
  { path: "/resources/moving-relocation-services", label: "Moving Relocation Services" },
  { path: "/senior-living/nursing-and-skilled-care", label: "Nursing And Skilled Care" },
  { path: "/olympia-probate-estate-real-estate", label: "Olympia Probate Estate" },
  { path: "/guides/out-of-state-families", label: "Out Of State Families" },
  { path: "/planning-before-a-crisis/conversations-to-have", label: "The Conversations Worth Having Now" },
  { path: "/planning-before-a-crisis/how-we-can-help", label: "How This Resource Helps" },
  { path: "/planning-before-a-crisis/legal-documents", label: "The Legal Documents That Matter Most" },
  { path: "/planning-before-a-crisis/property-questions", label: "The Property Questions to Think Through" },
  { path: "/planning-before-a-crisis/when-a-move-is-coming", label: "When a Move Seems Like It's Coming" },
  { path: "/planning-before-a-crisis/why-planning-early", label: "Why Planning Early Makes Such a Difference" },
  { path: "/counties/pacific", label: "Pacific County" },
  { path: "/pacific-county", label: "Pacific County" },
  { path: "/counties/pierce", label: "Pierce County" },
  { path: "/pierce-county", label: "Pierce County" },
  { path: "/planning", label: "Planning" },
  { path: "/planning-before-a-crisis", label: "Planning Before A Crisis" },
  { path: "/power-of-attorney", label: "Power Of Attorney" },
  { path: "/senior-living/power-of-attorneys", label: "Power Of Attorneys" },
  { path: "/preparing-home-for-sale-during-transition", label: "Preparing Home For Sale During Transition" },
  { path: "/guides/pricing-house-trust-estate", label: "Pricing House Trust Estate" },
  { path: "/professionals/probate-attorneys", label: "Probate Attorneys" },
  { path: "/resources/probate-estate-attorneys", label: "Probate Estate Attorneys" },
  { path: "/probate-estate-sales", label: "Probate Estate Sales" },
  { path: "/guides/probate-house-sale-timeline-washington", label: "Probate House Sale Timeline Washington" },
  { path: "/guides/probate-vs-trust-sale-washington", label: "Probate Vs Trust Sale Washington" },
  { path: "/professionals", label: "Professionals" },
  { path: "/professionals-services", label: "Professionals Page" },
  { path: "/resources/property-preparation-services", label: "Property Preparation Services" },
  {
    path: "/guides/repairs-before-selling-probate-home-washington",
    label: "Repairs Before Selling Probate Home Washington",
  },
  { path: "/", label: "Home" },
  { path: "/real-estate-appraiser", label: "Real Estate Appraiser" },
  { path: "/realtor", label: "Realtor" },
  { path: "/resources", label: "Find a Professional" },
  { path: "/retirement-reverse-mortgage", label: "Retirement Reverse Mortgage" },
  { path: "/roles", label: "Roles" },
  { path: "/counties/san-juan", label: "San Juan County" },
  { path: "/san-juan-county", label: "San Juan County" },
  { path: "/search", label: "Search" },
  { path: "/seattle-probate-estate-real-estate", label: "Seattle Probate Estate" },
  { path: "/guides/sell-house-during-probate-washington", label: "Sell House During Probate Washington" },
  { path: "/sell-house-fund-senior-living", label: "Sell House Fund Senior Living" },
  { path: "/guides/sell-inherited-house-as-is-or-fix", label: "Sell Inherited House As Is Or Fix" },
  { path: "/selling-an-inherited-home", label: "Selling An Inherited Home" },
  { path: "/professionals/senior-housing-advisors", label: "Senior Housing Advisors" },
  { path: "/articles/senior-housing-costs", label: "Senior Housing Costs" },
  { path: "/articles/senior-housing-guide", label: "Senior Housing Guide" },
  { path: "/articles/senior-housing-options", label: "Senior Housing Options" },
  { path: "/senior-living-advisors", label: "Senior Living Advisors" },
  { path: "/senior-living-and-relocation", label: "Senior Living And Relocation" },
  { path: "/resources/senior-living-communities", label: "Senior Living Communities" },
  { path: "/senior-move-managers", label: "Senior Move Managers Full" },
  { path: "/guides/senior-transition-differences", label: "Senior Transition Differences" },
  { path: "/senior-transitions", label: "Senior Transitions" },
  { path: "/articles/silver-tsunami", label: "Silver Tsunami" },
  { path: "/sitemap", label: "Sitemap" },
  { path: "/counties/skagit", label: "Skagit County" },
  { path: "/skagit-county", label: "Skagit County" },
  { path: "/counties/skamania", label: "Skamania County" },
  { path: "/skamania-county", label: "Skamania County" },
  { path: "/senior-living/skilled-nursing", label: "Skilled Nursing" },
  { path: "/counties/snohomish", label: "Snohomish County" },
  { path: "/snohomish-county", label: "Snohomish County" },
  { path: "/counties/spokane", label: "Spokane County" },
  { path: "/spokane-county", label: "Spokane County" },
  { path: "/spokane-probate-estate-real-estate", label: "Spokane Probate Estate" },
  { path: "/tacoma-probate-estate-real-estate", label: "Tacoma Probate Estate" },
  { path: "/guides/taxes-selling-inherited-house-washington", label: "Taxes Selling Inherited House Washington" },
  { path: "/terminology", label: "Terminology" },
  { path: "/testimonials", label: "Testimonials" },
  { path: "/counties/thurston", label: "Thurston County" },
  { path: "/thurston-county", label: "Thurston County" },
  { path: "/title-and-escrow", label: "Title And Escrow" },
  { path: "/trustees", label: "Trustees" },
  { path: "/understanding-housing-care-options", label: "Understanding Housing Care Options" },
  { path: "/understanding-senior-transitions", label: "Understanding Senior Transitions" },
  { path: "/vancouver-wa-probate-estate-real-estate", label: "Vancouver Wa Probate Estate" },
  { path: "/counties/wahkiakum", label: "Wahkiakum County" },
  { path: "/wahkiakum-county", label: "Wahkiakum County" },
  { path: "/resources/washington-executors-10-step-checklist", label: "Washington Executors Checklist" },
  { path: "/guides/what-executors-should-do", label: "What Executors Should Do" },
  { path: "/what-should-we-do-first", label: "What Should We Do First" },
  { path: "/what-to-do-with-the-house", label: "What To Do With The House" },
  { path: "/counties/whatcom", label: "Whatcom County" },
  { path: "/whatcom-county", label: "Whatcom County" },
  {
    path: "/guides/who-has-authority-sell-probate-property-washington",
    label: "Who Has Authority Sell Probate Property Washington",
  },
  { path: "/why-valuation-matters", label: "Why Valuation Matters" },
  { path: "/wills", label: "Wills" },
  { path: "/articles/wills-trusts-other-options", label: "Wills Trusts Other Options" },
  { path: "/counties/yakima", label: "Yakima County" },
  { path: "/yakima-county", label: "Yakima County" },
];
