import fs from 'fs';

const appSrc = fs.readFileSync('src/App.tsx', 'utf8');

const routeRe = /<Route\s+path=\{?"([^"]+)"\}?\s+element=\{<(\w+)/g;
const navRe = /<Route\s+path=\{?"([^"]+)"\}?\s+element=\{<Navigate to=\{?"([^"]+)"/g;
const routes = [];
const redirects = [];
let m;
while ((m = routeRe.exec(appSrc))) {
  if (m[2] === 'Navigate') continue;
  routes.push({ path: m[1], component: m[2] });
}
while ((m = navRe.exec(appSrc))) {
  redirects.push({ from: m[1], to: m[2] });
}

const compFile = {};
// lazy
const lazyRe = /const\s+(\w+)\s*=\s*lazy\(\(\)\s*=>\s*import\(\s*["']([^"']+)["']/g;
while ((m = lazyRe.exec(appSrc))) compFile[m[1]] = m[2];
// eager
const eagerRe = /import\s+(\w+)\s+from\s+["']([^"']+)["']/g;
while ((m = eagerRe.exec(appSrc))) compFile[m[1]] = m[2];

function resolveFile(rel) {
  if (!rel) return null;
  let p = rel.replace(/^\.\//, 'src/').replace(/^@\//, 'src/');
  for (const ext of ['.tsx', '.ts', '.jsx', '.js']) {
    if (fs.existsSync(p + ext)) return p + ext;
  }
  return null;
}

function extractLinks(file) {
  if (!file || !fs.existsSync(file)) return [];
  const src = fs.readFileSync(file, 'utf8');
  const links = new Set();
  const re1 = /\b(?:to|href)=["']([^"']+)["']/g;
  let mm;
  while ((mm = re1.exec(src))) {
    const u = mm[1];
    if (u.startsWith('/') && !u.startsWith('//')) {
      links.add(u.split('#')[0].split('?')[0]);
    }
  }
  return [...links].sort();
}

const seen = new Set();
const pages = [];
for (const r of routes) {
  if (seen.has(r.path)) continue;
  seen.add(r.path);
  const file = resolveFile(compFile[r.component]);
  pages.push({ path: r.path, links: extractLinks(file) });
}

pages.sort((a,b) => a.path.localeCompare(b.path));

fs.writeFileSync('src/data/sitemap-data.ts',
  '// AUTO-GENERATED by scripts/extract-sitemap.mjs — do not edit by hand.\n' +
  'export interface SitemapPage { path: string; links: string[]; }\n' +
  'export interface SitemapRedirect { from: string; to: string; }\n' +
  'export const SITEMAP_PAGES: SitemapPage[] = ' + JSON.stringify(pages, null, 2) + ';\n' +
  'export const SITEMAP_REDIRECTS: SitemapRedirect[] = ' + JSON.stringify(redirects, null, 2) + ';\n'
);
console.log('pages:', pages.length, 'redirects:', redirects.length);
