// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CONTACT = {
  business: "Real Property Planning",
  phone: "(206) 900-3015",
  email: "info@realpropertyplanning.com",
  website: "https://www.realpropertyplanning.com",
  service_area: "Washington State (with a focus on Western Washington and the Puget Sound region)",
  brokerage: "eXp Realty (Washington State Licensed Real Estate Broker)",
  appraisal: "Stein Appraisal (Washington State Certified Residential Appraiser)"
};
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return contact information for Real Property Planning \u2014 phone, email, website, and service area.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  { name: "Probate & Estate Sales", url: "/probate-estate-sales", audience: "Executors, attorneys, families" },
  { name: "Support for Executors", url: "/executors", audience: "Executors managing inherited property" },
  { name: "Senior Housing Transitions", url: "/senior-transitions", audience: "Seniors and families downsizing or relocating" },
  { name: "Attorney Referral Resource", url: "/for-attorneys", audience: "Estate, probate, and family law attorneys" },
  { name: "Real Estate Guidance for CPAs", url: "/for-cpas", audience: "CPAs and their clients" },
  { name: "Real Estate Guidance for Financial Planners", url: "/for-financial-planners", audience: "Financial planners and their clients" },
  { name: "Property Valuation", url: "/why-valuation-matters", audience: "Attorneys, executors, trustees" },
  { name: "Join the Professional Network", url: "/join-network", audience: "Professionals serving seniors and estates" }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "List services",
  description: "List the core services offered by Real Property Planning with a short audience description and page path.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/list-service-areas.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var COUNTIES = [
  { name: "King County", url: "/king-county", cities: ["Seattle", "Bellevue", "Kirkland", "Redmond", "Mercer Island", "Issaquah", "Renton"] },
  { name: "Snohomish County", url: "/snohomish-county", cities: ["Everett", "Edmonds", "Lynnwood", "Mukilteo", "Mill Creek", "Monroe"] },
  { name: "Pierce County", url: "/pierce-county", cities: ["Tacoma", "Gig Harbor", "Puyallup", "University Place"] },
  { name: "Kitsap County", url: "/kitsap-county", cities: ["Bainbridge Island", "Poulsbo", "Silverdale", "Bremerton"] },
  { name: "Skagit County", url: "/skagit-county", cities: ["Mount Vernon", "Burlington", "Anacortes"] }
];
var list_service_areas_default = defineTool4({
  name: "list_service_areas",
  title: "List service areas",
  description: "List Washington State counties served by Real Property Planning, with representative cities and page paths.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COUNTIES, null, 2) }],
    structuredContent: { counties: COUNTIES }
  })
});

// src/lib/mcp/index.ts
var projectRef = "zgmoiivyxzppnrpksmfg";
var mcp_default = defineMcp({
  name: "real-property-planning-mcp",
  title: "Real Property Planning MCP",
  version: "0.1.0",
  instructions: "Tools for Real Property Planning \u2014 a Washington State probate, estate, and senior-transition real estate resource. Use `get_contact_info` for business contact details, `list_services` to see offered services, `list_service_areas` for counties and cities served, and `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, get_contact_info_default, list_services_default, list_service_areas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
