// AUTO-GENERATED by scripts/extract-sitemap.mjs — do not edit by hand.
export interface SitemapPage { path: string; links: string[]; }
export interface SitemapRedirect { from: string; to: string; }
export const SITEMAP_PAGES: SitemapPage[] = [
  {
    "path": "*",
    "links": [
      "/",
      "/guides-and-resources"
    ]
  },
  {
    "path": "/",
    "links": []
  },
  {
    "path": "/about",
    "links": [
      "/contact",
      "/counties",
      "/executors",
      "/probate-estate-sales",
      "/real-estate-appraiser",
      "/senior-transitions",
      "/testimonials"
    ]
  },
  {
    "path": "/aging-in-place-staying-home-safely",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/bellevue-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/bellingham-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/benton-county",
    "links": []
  },
  {
    "path": "/building-your-trusted-professional-team",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/clark-county",
    "links": []
  },
  {
    "path": "/client-stories",
    "links": []
  },
  {
    "path": "/contact",
    "links": []
  },
  {
    "path": "/counties",
    "links": [
      "/cities-we-serve",
      "/contact"
    ]
  },
  {
    "path": "/counties/benton",
    "links": []
  },
  {
    "path": "/counties/clark",
    "links": []
  },
  {
    "path": "/counties/cowlitz",
    "links": []
  },
  {
    "path": "/counties/franklin",
    "links": []
  },
  {
    "path": "/counties/grays-harbor",
    "links": []
  },
  {
    "path": "/counties/island",
    "links": []
  },
  {
    "path": "/counties/jefferson",
    "links": []
  },
  {
    "path": "/counties/king",
    "links": []
  },
  {
    "path": "/counties/kitsap",
    "links": []
  },
  {
    "path": "/counties/lewis",
    "links": []
  },
  {
    "path": "/counties/mason",
    "links": []
  },
  {
    "path": "/counties/pacific",
    "links": []
  },
  {
    "path": "/counties/pierce",
    "links": []
  },
  {
    "path": "/counties/san-juan",
    "links": []
  },
  {
    "path": "/counties/skagit",
    "links": []
  },
  {
    "path": "/counties/skamania",
    "links": []
  },
  {
    "path": "/counties/snohomish",
    "links": []
  },
  {
    "path": "/counties/spokane",
    "links": []
  },
  {
    "path": "/counties/thurston",
    "links": []
  },
  {
    "path": "/counties/wahkiakum",
    "links": []
  },
  {
    "path": "/counties/whatcom",
    "links": []
  },
  {
    "path": "/counties/yakima",
    "links": []
  },
  {
    "path": "/cowlitz-county",
    "links": []
  },
  {
    "path": "/date-of-death-valuation-property-appraisals",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/downsizing-preparing-for-transition",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/estate-liquidation",
    "links": [
      "/contact",
      "/estate-liquidation/learn-more"
    ]
  },
  {
    "path": "/estate-liquidation/learn-more",
    "links": [
      "/contact",
      "/estate-liquidation"
    ]
  },
  {
    "path": "/estate-planning-powers-of-attorney",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/estate-probate-inherited-property",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/first-steps",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/preparing-the-property",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/probate-and-legal-authority",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/professional-team",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/property-value",
    "links": []
  },
  {
    "path": "/estate-probate-inherited-property/what-to-do-with-the-property",
    "links": []
  },
  {
    "path": "/everett-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/executor-responsibilities-first-steps",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/common-mistakes",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/first-30-days",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/legal-duties",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/property-decisions",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/when-you-need-extra-help",
    "links": []
  },
  {
    "path": "/executor-responsibilities-first-steps/working-with-professionals",
    "links": []
  },
  {
    "path": "/executors",
    "links": [
      "/contact",
      "/counties",
      "/guides/executor-first-steps-house",
      "/guides/executor-sell-before-probate",
      "/guides/heirs-disagree-selling",
      "/guides/out-of-state-families",
      "/guides/sell-house-during-probate-washington",
      "/resources/washington-executors-10-step-checklist"
    ]
  },
  {
    "path": "/faq",
    "links": [
      "/contact",
      "/guides/appraisal-vs-cma",
      "/guides/how-probate-real-estate-works",
      "/guides/inherited-house-washington",
      "/guides/out-of-state-families",
      "/guides/senior-transition-differences",
      "/guides/what-executors-should-do"
    ]
  },
  {
    "path": "/for-attorneys",
    "links": [
      "/for-attorneys/how-it-works",
      "/for-attorneys/learn-more"
    ]
  },
  {
    "path": "/for-attorneys/divorce-attorneys",
    "links": [
      "/contact",
      "/counties",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/for-attorneys/elder-law-attorneys",
    "links": [
      "/contact",
      "/counties",
      "/real-estate-appraiser",
      "/senior-living/memory-care",
      "/senior-transitions"
    ]
  },
  {
    "path": "/for-attorneys/estate-planning-attorneys",
    "links": [
      "/contact",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/for-attorneys/family-law-attorneys",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/for-attorneys/how-it-works",
    "links": [
      "/contact",
      "/for-attorneys"
    ]
  },
  {
    "path": "/for-attorneys/probate-attorneys",
    "links": [
      "/contact",
      "/executors",
      "/probate-estate-sales",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/for-attorneys/real-estate-attorneys",
    "links": [
      "/contact",
      "/counties"
    ]
  },
  {
    "path": "/for-cpas",
    "links": [
      "/for-cpas/learn-more"
    ]
  },
  {
    "path": "/for-divorce-attorneys",
    "links": [
      "/contact",
      "/counties",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/for-elder-law-attorneys",
    "links": [
      "/contact",
      "/counties",
      "/real-estate-appraiser",
      "/senior-living/memory-care",
      "/senior-transitions"
    ]
  },
  {
    "path": "/for-estate-planning-attorneys",
    "links": [
      "/contact",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/for-family-law-attorneys",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/for-financial-planners",
    "links": [
      "/for-financial-planners/learn-more"
    ]
  },
  {
    "path": "/for-probate-attorneys",
    "links": [
      "/contact",
      "/executors",
      "/probate-estate-sales",
      "/real-estate-appraiser"
    ]
  },
  {
    "path": "/franklin-county",
    "links": []
  },
  {
    "path": "/gray-divorce",
    "links": [
      "/contact",
      "/for-divorce-attorneys"
    ]
  },
  {
    "path": "/grays-harbor-county",
    "links": []
  },
  {
    "path": "/grey-divorce",
    "links": [
      "/for-attorneys"
    ]
  },
  {
    "path": "/guides-and-resources",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/guides/appraisal-before-selling-inherited-property",
    "links": [
      "/contact",
      "/executors",
      "/guides/appraisal-vs-cma",
      "/guides/inherited-house-washington",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/appraisal-vs-cma",
    "links": [
      "/contact",
      "/executors",
      "/for-attorneys",
      "/guides/how-probate-real-estate-works",
      "/how-the-process-works",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/estate-property-repairs-before-sale",
    "links": [
      "/contact",
      "/executors",
      "/guides/what-executors-should-do",
      "/probate-estate-sales",
      "/resources/property-preparation-services",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/executor-first-steps-house",
    "links": [
      "/contact",
      "/executors",
      "/guides/how-long-sell-probate-property",
      "/guides/what-executors-should-do",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/executor-sell-house-before-probate-washington",
    "links": [
      "/contact",
      "/executors",
      "/guides/how-probate-real-estate-works",
      "/guides/what-executors-should-do",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/heirs-disagree-selling-house",
    "links": [
      "/contact",
      "/executors",
      "/guides/how-probate-real-estate-works",
      "/guides/inherited-house-washington",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/how-long-sell-probate-property",
    "links": [
      "/contact",
      "/executors",
      "/guides/executor-first-steps-house",
      "/guides/sell-house-during-probate-washington",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/how-probate-real-estate-works",
    "links": []
  },
  {
    "path": "/guides/inherited-house-washington",
    "links": []
  },
  {
    "path": "/guides/out-of-state-families",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/guides/pricing-house-trust-estate",
    "links": [
      "/contact",
      "/executors",
      "/guides/appraisal-before-selling-inherited-property",
      "/guides/appraisal-vs-cma",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/probate-house-sale-timeline-washington",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/guides/probate-vs-trust-sale-washington",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/guides/repairs-before-selling-probate-home-washington",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/guides/sell-house-during-probate-washington",
    "links": [
      "/contact",
      "/executors",
      "/guides/executor-sell-house-before-probate-washington",
      "/guides/how-probate-real-estate-works",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/sell-inherited-house-as-is-or-fix",
    "links": [
      "/contact",
      "/executors",
      "/guides/estate-property-repairs-before-sale",
      "/guides/pricing-house-trust-estate",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/senior-transition-differences",
    "links": [
      "/contact",
      "/how-the-process-works",
      "/how-to-move-elderly-parents",
      "/resources/senior-living-communities",
      "/senior-move-managers",
      "/senior-transitions",
      "/testimonials"
    ]
  },
  {
    "path": "/guides/taxes-selling-inherited-house-washington",
    "links": [
      "/contact",
      "/executors",
      "/guides/inherited-house-washington",
      "/guides/pricing-house-trust-estate",
      "/probate-estate-sales",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/what-executors-should-do",
    "links": [
      "/contact",
      "/executors",
      "/for-attorneys",
      "/guides/how-probate-real-estate-works",
      "/guides/inherited-house-washington",
      "/guides/out-of-state-families",
      "/how-the-process-works",
      "/resources/estate-sale-companies",
      "/resources/property-preparation-services",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/guides/who-has-authority-sell-probate-property-washington",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/helping-aging-parents",
    "links": [
      "/contact",
      "/helping-an-aging-parent"
    ]
  },
  {
    "path": "/helping-an-aging-parent",
    "links": [
      "/contact",
      "/helping-an-aging-parent"
    ]
  },
  {
    "path": "/helping-an-aging-parent/*",
    "links": [
      "/contact",
      "/helping-an-aging-parent"
    ]
  },
  {
    "path": "/how-the-process-works",
    "links": [
      "/contact",
      "/executors",
      "/faq",
      "/for-attorneys",
      "/guides/out-of-state-families",
      "/probate-estate-sales",
      "/real-estate-appraiser",
      "/senior-transitions",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/island-county",
    "links": []
  },
  {
    "path": "/jefferson-county",
    "links": []
  },
  {
    "path": "/join-the-network",
    "links": []
  },
  {
    "path": "/king-county",
    "links": []
  },
  {
    "path": "/kitsap-county",
    "links": []
  },
  {
    "path": "/lenders-and-financing-specialists",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/lewis-county",
    "links": []
  },
  {
    "path": "/mason-county",
    "links": []
  },
  {
    "path": "/medicare-providers",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/olympia-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/pacific-county",
    "links": []
  },
  {
    "path": "/pierce-county",
    "links": []
  },
  {
    "path": "/planning",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/conversations-to-have",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/how-we-can-help",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/legal-documents",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/property-questions",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/when-a-move-is-coming",
    "links": []
  },
  {
    "path": "/planning-before-a-crisis/why-planning-early",
    "links": []
  },
  {
    "path": "/power-of-attorney",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/preparing-home-for-sale-during-transition",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/probate-estate-sales",
    "links": [
      "/faq",
      "/how-the-process-works",
      "/terminology"
    ]
  },
  {
    "path": "/professionals",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/professionals-services",
    "links": []
  },
  {
    "path": "/professionals/care-managers",
    "links": []
  },
  {
    "path": "/professionals/estate-sale",
    "links": []
  },
  {
    "path": "/professionals/financial-planners",
    "links": []
  },
  {
    "path": "/professionals/home-preparation",
    "links": []
  },
  {
    "path": "/professionals/probate-attorneys",
    "links": []
  },
  {
    "path": "/professionals/senior-housing-advisors",
    "links": []
  },
  {
    "path": "/real-estate-appraiser",
    "links": [
      "/real-estate-appraiser/learn-more"
    ]
  },
  {
    "path": "/real-estate-attorneys",
    "links": [
      "/contact",
      "/counties"
    ]
  },
  {
    "path": "/realtor",
    "links": [
      "/realtor/learn-more"
    ]
  },
  {
    "path": "/resources",
    "links": []
  },
  {
    "path": "/resources/cpas-financial-advisors",
    "links": [
      "/contact",
      "/for-cpas",
      "/for-financial-planners",
      "/why-valuation-matters"
    ]
  },
  {
    "path": "/resources/estate-sale-companies",
    "links": [
      "/contact",
      "/probate-estate-sales"
    ]
  },
  {
    "path": "/resources/moving-relocation-services",
    "links": [
      "/contact",
      "/senior-transitions"
    ]
  },
  {
    "path": "/resources/probate-estate-attorneys",
    "links": [
      "/contact",
      "/executors",
      "/for-attorneys"
    ]
  },
  {
    "path": "/resources/property-preparation-services",
    "links": [
      "/contact",
      "/how-the-process-works"
    ]
  },
  {
    "path": "/resources/senior-living-communities",
    "links": [
      "/contact",
      "/senior-transitions"
    ]
  },
  {
    "path": "/resources/washington-executors-10-step-checklist",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/retirement-reverse-mortgage",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/roles",
    "links": []
  },
  {
    "path": "/san-juan-county",
    "links": []
  },
  {
    "path": "/seattle-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/sell-house-fund-senior-living",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/selling-an-inherited-home",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/senior-living-and-relocation",
    "links": []
  },
  {
    "path": "/senior-living/adult-family-homes",
    "links": []
  },
  {
    "path": "/senior-living/aging-in-place",
    "links": []
  },
  {
    "path": "/senior-living/assisted-living",
    "links": []
  },
  {
    "path": "/senior-living/assisted-living-communities",
    "links": [
      "/contact",
      "/senior-living-and-relocation"
    ]
  },
  {
    "path": "/senior-living/independent-living",
    "links": []
  },
  {
    "path": "/senior-living/memory-care",
    "links": []
  },
  {
    "path": "/senior-living/nursing-and-skilled-care",
    "links": [
      "/contact",
      "/senior-living-and-relocation"
    ]
  },
  {
    "path": "/senior-living/power-of-attorneys",
    "links": [
      "/contact",
      "/executors",
      "/for-attorneys",
      "/probate-estate-sales",
      "/senior-transitions"
    ]
  },
  {
    "path": "/senior-living/skilled-nursing",
    "links": []
  },
  {
    "path": "/senior-move-managers",
    "links": [
      "/senior-move-managers/learn-more"
    ]
  },
  {
    "path": "/senior-placement",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/senior-transitions",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/skagit-county",
    "links": []
  },
  {
    "path": "/skamania-county",
    "links": []
  },
  {
    "path": "/snohomish-county",
    "links": []
  },
  {
    "path": "/spokane-county",
    "links": []
  },
  {
    "path": "/spokane-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/tacoma-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/terminology",
    "links": []
  },
  {
    "path": "/testimonials",
    "links": []
  },
  {
    "path": "/thurston-county",
    "links": []
  },
  {
    "path": "/title-and-escrow",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/trustees",
    "links": [
      "/contact",
      "/trustees/learn-more"
    ]
  },
  {
    "path": "/understanding-housing-care-options",
    "links": []
  },
  {
    "path": "/understanding-senior-transitions",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/vancouver-wa-probate-estate-real-estate",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/wahkiakum-county",
    "links": []
  },
  {
    "path": "/what-should-we-do-first",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/what-to-do-with-the-house",
    "links": []
  },
  {
    "path": "/whatcom-county",
    "links": []
  },
  {
    "path": "/why-valuation-matters",
    "links": []
  },
  {
    "path": "/wills",
    "links": [
      "/contact"
    ]
  },
  {
    "path": "/yakima-county",
    "links": []
  }
];
export const SITEMAP_REDIRECTS: SitemapRedirect[] = [
  {
    "from": "/out-of-state-families",
    "to": "/guides/out-of-state-families"
  },
  {
    "from": "/about-david-stein",
    "to": "/about"
  },
  {
    "from": "/about-platform",
    "to": "/about"
  },
  {
    "from": "/kirkland-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/redmond-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/renton-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/kent-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/federal-way-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/auburn-probate-estate-real-estate",
    "to": "/king-county"
  },
  {
    "from": "/marysville-probate-estate-real-estate",
    "to": "/snohomish-county"
  },
  {
    "from": "/yakima-probate-estate-real-estate",
    "to": "/yakima-county"
  },
  {
    "from": "/kennewick-probate-estate-real-estate",
    "to": "/benton-county"
  },
  {
    "from": "/richland-probate-estate-real-estate",
    "to": "/benton-county"
  },
  {
    "from": "/pasco-probate-estate-real-estate",
    "to": "/franklin-county"
  },
  {
    "from": "/cities-we-serve",
    "to": "/counties"
  },
  {
    "from": "/cities/:citySlug",
    "to": "/counties"
  },
  {
    "from": "/cities/:citySlug/:serviceSlug",
    "to": "/counties"
  },
  {
    "from": "/probate-sales",
    "to": "/probate-estate-sales"
  },
  {
    "from": "/services",
    "to": "/probate-estate-sales"
  },
  {
    "from": "/services/probate-estate-sales",
    "to": "/probate-estate-sales"
  },
  {
    "from": "/services/senior-transitions",
    "to": "/senior-transitions"
  },
  {
    "from": "/services/downsizing-services",
    "to": "/senior-transitions"
  },
  {
    "from": "/services/executor-support",
    "to": "/executors"
  },
  {
    "from": "/services/attorney-fiduciary-support",
    "to": "/for-attorneys"
  },
  {
    "from": "/services/valuation-guidance",
    "to": "/why-valuation-matters"
  },
  {
    "from": "/services/preparing-home-for-sale",
    "to": "/probate-estate-sales"
  },
  {
    "from": "/services/divorce-related-home-sales",
    "to": "/for-divorce-attorneys"
  },
  {
    "from": "/services/trust-estate-property-sales",
    "to": "/trustees"
  },
  {
    "from": "/insights",
    "to": "/guides-and-resources"
  },
  {
    "from": "/insights/first-steps-inherited-house-washington",
    "to": "/guides/executor-first-steps-house"
  },
  {
    "from": "/insights/out-of-state-inherited-house-help",
    "to": "/guides/out-of-state-families"
  },
  {
    "from": "/insights/out-of-state-executor-case-study",
    "to": "/guides/out-of-state-families"
  },
  {
    "from": "/insights/estate-property-sale-timeline",
    "to": "/guides/how-long-sell-probate-property"
  },
  {
    "from": "/insights/estate-property-cleanout-before-sale",
    "to": "/guides/estate-property-repairs-before-sale"
  },
  {
    "from": "/insights/empty-house-before-selling",
    "to": "/guides/estate-property-repairs-before-sale"
  },
  {
    "from": "/insights/pricing-inherited-property-differences",
    "to": "/guides/pricing-house-trust-estate"
  },
  {
    "from": "/insights/sell-inherited-house-without-repairs",
    "to": "/guides/sell-inherited-house-as-is-or-fix"
  },
  {
    "from": "/insights/family-disagreement-selling-house",
    "to": "/guides/heirs-disagree-selling-house"
  },
  {
    "from": "/insights/sell-or-keep-inherited-property",
    "to": "/guides/sell-inherited-house-as-is-or-fix"
  },
  {
    "from": "/insights/estate-property-mistakes",
    "to": "/guides/what-executors-should-do"
  },
  {
    "from": "/insights-guidance/how-does-probate-real-estate-work-in-washington",
    "to": "/guides/how-probate-real-estate-works"
  },
  {
    "from": "/insights-guidance/how-to-move-elderly-parents-safely-and-respectfully",
    "to": "/guides/senior-transition-differences"
  },
  {
    "from": "/how-to-move-elderly-parents",
    "to": "/guides/senior-transition-differences"
  },
  {
    "from": "/executors/learn-more",
    "to": "/executors"
  },
  {
    "from": "/trustees/learn-more",
    "to": "/trustees"
  },
  {
    "from": "/for-attorneys/learn-more",
    "to": "/for-attorneys"
  },
  {
    "from": "/for-cpas/learn-more",
    "to": "/for-cpas"
  },
  {
    "from": "/for-financial-planners/learn-more",
    "to": "/for-financial-planners"
  },
  {
    "from": "/realtor/learn-more",
    "to": "/realtor"
  },
  {
    "from": "/real-estate-appraiser/learn-more",
    "to": "/real-estate-appraiser"
  },
  {
    "from": "/senior-move-managers/learn-more",
    "to": "/senior-transitions"
  },
  {
    "from": "/estate-liquidation/learn-more",
    "to": "/estate-liquidation"
  },
  {
    "from": "/professional-referral-resource",
    "to": "/join-the-network"
  },
  {
    "from": "/professional-network",
    "to": "/building-your-trusted-professional-team"
  },
  {
    "from": "/attorney-referral",
    "to": "/for-attorneys"
  },
  {
    "from": "/for-referral-partners",
    "to": "/join-the-network"
  },
  {
    "from": "/for-professionals",
    "to": "/professionals"
  },
  {
    "from": "/for-senior-living-professionals",
    "to": "/professionals/senior-housing-advisors"
  },
  {
    "from": "/senior-estate-services",
    "to": "/senior-transitions"
  },
  {
    "from": "/transition-resources",
    "to": "/senior-transitions"
  },
  {
    "from": "/how-we-work",
    "to": "/how-the-process-works"
  },
  {
    "from": "/cpas",
    "to": "/for-cpas"
  },
  {
    "from": "/financial-planning",
    "to": "/for-financial-planners"
  },
  {
    "from": "/senior-living",
    "to": "/senior-living-and-relocation"
  },
  {
    "from": "/lenders-financing",
    "to": "/lenders-and-financing-specialists"
  }
];
